apiVersion: v1
kind: Service
metadata:
  name: aurofy-service
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: aurofy
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aurofy-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aurofy
  template:
    metadata:
      labels:
        app: aurofy
    spec:
      containers:
        - name: aurofy
          image: <your-image-repo>/aurofy:latest
          ports:
            - containerPort: 8080
